### PR TITLE
feat: Use TELEGRAM_HTTP_PORT env to set the api server listening port

### LINKED ISSUE #13: feat: Customizing http ports via env
I started the image, but since the network mode is not using host, the api server is not able to send the webhook to the service on host.

However, if host mode is used, 8081 will be directly occupied since the http port cannot be customized via env in the configuration file.

The current solution seems to be to build another image from the image itself, is it possible to set the http port via env?

Thank you.

### PR DESCRIPTION
**Pull request by kiki-kanri**
Closed #13

### CODE REVIEW

**Review by JrooTJunior — DISMISSED** [review]

**Comment by kiki-kanri** [comment]
I'm sorry, is there something I need to change but I'm missing it?

If there is, please tell me and I'll change it immediately, thanks!

Also, I built it myself and it works fine.

**Comment by JrooTJunior** [comment]
@kiki-kanri, why did you close this PR? My message above ("mistake") is about my approvement before i test it, but i still think this feature can be useful, so i need to have time to test it. Could you open it again?

**Comment by kiki-kanri** [comment]
> @kiki-kanri, why did you close this PR? My message above ("mistake") is about my approvement before i test it, but i still think this feature can be useful, so i need to have time to test it. Could you open it again?

I'm sorry, I misunderstood what you meant before, since I deleted the forked project, I need some time to deal with it (after I get off work), I'll reopen the PR after I'm done, thanks!

**Comment by kiki-kanri** [comment]
PR has been reopened (#14), please test and review again. Thank you!

**Pull request closed without merging**
